### ISSUE TITLE
Step 5 git checkout v1.8.0 command

### ISSUE THREAD

**Issue by otieno-o** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#1]
When this command is entered while in /tensorflow1/models/ it deletes all previous downloaded files in models/research with exception of syntaxnet. I think this isnt the desired effect? Right? If I am correct, how what would I be doing wrong thus the result.  I choose to ignore the message, wise choice? Thanks

**Comment by EdjeElectronics** [comment]
I'm not sure why it's doing that. I will remove the instruction to issue "git checkout v1.8.0" for now, and investigate later today. Thanks for the heads up!

**Comment by otieno-o** [comment]
No, thank you for fast response.
