### ISSUE TITLE
Movidius NCS

### ISSUE THREAD

**Issue by 3073** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#13]
I have tested a similar code( Tensorflow SSD model on my raspberry pi with dlib tracker) on my raspberry pi and it works fine but it is still slow. so I decide to use NCS movidius... Have you tried it? where should I start?

**Comment by treinberger** [comment]
Have a look at https://github.com/PINTO0309/MobileNet-SSD-RealSense if you have got a USB Cam or at https://gist.github.com/treinberger/c63cb84979a4b3fb9b13a2d290482f4e if you've got a PiCam.

**Comment by EdjeElectronics** [comment]
Cool, thanks for sharing these @treinberger!
