### ISSUE TITLE
Step 6: python3 Object_detection_picamera.py 

### ISSUE THREAD

**Issue by otieno-o** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#2]
Please note I followed the tutorial step by step apart from ignoring step 3 'git checkout v1.8.0', it resulted to deletion of previously downloaded files as highlighted in issue 1. Again very grateful to your efforts @EdjeElectronics . 
Running the command 'python3 Object_detection_picamera.py ' generated the following error. 
![image](https://user-images.githubusercontent.com/38064258/41549704-a882c1a4-7361-11e8-9b87-45fc564ff072.png) What would be the best foot forward? Thanks

Some notes:
(Not sure if relevant) On checking the files (not sure if what I didnt was correct) i noticed there is no file with 'string_int_label_map_pb2' but found 'string_int_label_map.proto'.

**Comment by EdjeElectronics** [comment]
Shoot! I forgot to put a critical step in the instructions. All the protobuf files need to be converted from .proto to _pb2.py . I'll look at it, add a step, and update when it's fixed!

**Comment by EdjeElectronics** [comment]
Okay, I added instructions in Step 5 to issue a "protoc" command that converts all the .proto files into _pb2.py files. Can you try issuing the following commands and then seeing if Object_detection_picamera.py works?

cd /home/pi/tensorflow1/models/research
protoc object_detection/protos/*.proto --python_out=.

**Comment by otieno-o** [comment]
Works like magic..Thanks
