### ISSUE TITLE
ImportError: libvtkInteractionStyle-6.3.so.6.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rdoebler** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#23]
Hi! I am getting the following error when I try to run step 6:

ImportError: libvtkInteractionStyle-6.3.so.6.3: cannot open shared object file: No such file or directory

Any idea how to resolve this? Thanks!

**Comment by EdjeElectronics** [comment]
Hi @rdoebler, do you mind sharing how you fixed the issue? 😄

**Comment by rdoebler** [comment]
Sorry, yes! 😄 . I was missing an OpenCV package on my Rasberry Pi 3 on Raspbian Stretch. I you can get the library above by running:

```
sudo apt-get install libvtk6.3
```

**Comment by pierreramiro** [comment]
Also, For me was necessary to running:
`sudo apt-get install libvtkgdcm-dev`
