### ISSUE TITLE
Question not an Issue, How long did you train your playing card detector model?

### ISSUE THREAD

**Issue by Twikkxx** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#39]
How long did you train the playing card detector model to accurately detect the playing card?

**Comment by EdjeElectronics** [comment]
I trained it for about 8 hours on my PC. I used about 800 training images total. My PC has these specs:

GPU: GeForce GTX 1060 6Gb
CPU: Intel i5-7600
RAM: 16GB DDR4-2133

While the playing card detector model works fairly well, it still is only about 90% accurate.
