### ISSUE TITLE
tensorflow 

### ISSUE THREAD

**Issue by 3073** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#5]
Hi  !!!  I am a little bit confused !!!!
What is the difference between tensorflow object detection API and SSD Mobile net ( written in tensorflow)? are they the same thing?

**Comment by EdjeElectronics** [comment]
Hello! SSD_MobileNet is a detection model, which is a neural network that has been pre-trained to detect certain objects in images. When you pass an input image into the SSD_MobileNet model, it spits out an "answer" that tells you which objects were detected and their location in the image.

The TensorFlow Object Detection API is a tool that allows you to easily load a detection model (such as SSD_MobileNet) into a TensorFlow program, pass images into the model, and get the output "answers" from the model.

Reading through these might help clarify things more:
https://github.com/tensorflow/models/tree/master/research/object_detection
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

I hope this helps!
