### ISSUE TITLE
<!DOCTYPE html> SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by reokyouma** [EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi#63]
` File "Object_detection_picamera.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`

Hi i am getting this error, how can i resolve this?

**Comment by EdjeElectronics** [comment]
You somehow downloaded the GitHub HTML file for Object_detection_picamera.py, rather than the script itself. Delete the Object_detection_picamera.py file, then re-download it using:

```
wget https://raw.githubusercontent.com/EdjeElectronics/TensorFlow-Object-Detection-on-the-Raspberry-Pi/master/Object_detection_picamera.py
```

Then, try running the script.
